version: '2.0'
services:
  proxy:
    build: proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - "443:4443"
      - "80:8080"
    volumes:
      - /etc/letsencrypt/:/var/tls:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - docker-network
  website:
    build: website
    container_name: website
    restart: unless-stopped
    networks:
      - docker-network
networks:
  docker-network:
    external:
      name: docker-network
